version: '3.7'

services:
  client:
    build:
      context: client
      dockerfile: Dockerfile
    container_name: client
    stdin_open: true
    env_file:
      - client.env
    ports:
      - '3000:3000'
    volumes:
      - ./client:/client/app
      - /client/node_modules
    networks:
      - full_stack_net
    depends_on:
      - server

  server:
    build:
      context: server
      dockerfile: Dockerfile
    container_name: server
    env_file:
      - server.env
    ports:
      - '5000:5000'
    volumes:
      - ./server:/server
      - /server/node_modules
    networks:
      - full_stack_net

networks:
  full_stack_net:
    name: full_stack_net

